/* Code generated by packages/contract/codegen/generate.py. DO NOT EDIT. */

export const PROTOCOL_VERSION = 1 as const;
export const SCHEMA_ID = "https://schemas.vodoge.cloud/edge-cloud/v1/edge-cloud.schema.json" as const;
export const WS_SUBPROTOCOL = "vodoge.edge.v1" as const;

export type EpochMillis = number;
export type SequenceNumber = string;
export type SequenceCursor = string;
export type Uuid = string;
export type Iccid = string;
export type Imsi = string;
export type Plmn = string;
export type Imei = string;
export type Sha256 = string;
export type HttpsUrl = string;

export type MessageKind =
  | "Resume" |
  | "ResumeAck" |
  | "UplinkAck" |
  | "UplinkGap" |
  | "UplinkGapAck" |
  | "Ping" |
  | "Pong" |
  | "CommandDeliver" |
  | "CommandReceipt" |
  | "SmsReceived" |
  | "DeviceState" |
  | "CommandResult" |
  | "EsimInventory" |
  | "Alert" |
  | "ProxyTraffic" |
  | "ProtocolError";

export const SEQUENCED_KINDS: ReadonlySet<MessageKind> = new Set([
  "SmsReceived",
  "DeviceState",
  "CommandResult",
  "EsimInventory",
  "Alert",
  "ProxyTraffic",
]);

export type ContextValue =
  | null
  | boolean
  | number
  | string
  | ContextValue[]
  | { [key: string]: ContextValue };

export interface Envelope {
  v: 1;
  kind: MessageKind;
  id: Uuid;
  ts: EpochMillis;
  device_id: Uuid;
  seq?: SequenceNumber;
  trace_id?: Uuid;
  payload: unknown;
}

export interface SequenceRange {
  from: string;
  through: string;
}

export interface ResumePayload {
  connection_id: Uuid;
  last_assigned_seq: string;
  lowest_retained_seq: string | null;
  last_acked_seq: string;
  pending_gap_ids: Array<Uuid>;
  capability_matrix_version: string;
  edge_version?: string;
  queue_records?: number;
  queue_bytes?: number;
}

export interface ResumeAckPayload {
  connection_id: Uuid;
  committed_through: string;
  missing_ranges: Array<SequenceRange>;
  more_missing: boolean;
  max_in_flight: number;
  server_time: number;
}

export interface UplinkAckPayload {
  connection_id: Uuid;
  committed_through: string;
  missing_ranges: Array<SequenceRange>;
  more_missing: boolean;
  max_in_flight: number;
}

export interface UplinkGapPayload {
  gap_id: Uuid;
  ranges: Array<SequenceRange>;
  reason: "queue_capacity" | "storage_corruption" | "operator_purge";
  dropped_records: number;
  occurred_at: number;
  drop_policy: "oldest_non_verification_only";
  detail?: string | null;
}

export interface UplinkGapAckPayload {
  gap_id: Uuid;
  accepted: boolean;
  committed_through: string;
  reason_code?: string | null;
}

export interface PingPayload {
  connection_id: Uuid;
  sent_at: number;
}

export interface PongPayload {
  connection_id: Uuid;
  ping_id: Uuid;
  server_time: number;
}

export interface CommandDeliverPayload {
  cmd_id: Uuid;
  issued_at: number;
  expires_at: number;
  attempt?: number;
  command: Command;
}

export interface CommandReceiptPayload {
  cmd_id: Uuid;
  delivery_id: Uuid;
  status: "accepted" | "duplicate" | "retry_later";
  received_at: number;
  retry_after_ms?: number;
  reason_code?: string | null;
}

export interface SmsReceivedPayload {
  modem_imei: Imei;
  peer: string;
  body: string;
  received_at: number;
  iccid: Iccid;
  bearer: "cs" | "ims" | "nas" | "unknown";
  encoding: "gsm7" | "ucs2" | "8bit" | "unknown";
  modem_storage_index?: number;
}

export interface ProxyTrafficPayload {
  reported_at: number;
  instances: Array<ProxyTrafficEntry>;
}

export interface ProxyTrafficEntry {
  instance_id: Uuid;
  bytes_up: number;
  bytes_down: number;
  connections: number;
  errors?: number;
}

export interface DeviceStatePayload {
  observed_at: number;
  modems: Array<ModemState>;
  host?: HostState | null;
}

export interface HostState {
  public_ip?: string | null;
  cpu_percent?: number | null;
  memory_used_bytes?: number | null;
  memory_total_bytes?: number | null;
}

export interface ModemState {
  modem_imei: Imei;
  state: "online" | "offline" | "recovering" | "unknown";
  registration: "registered" | "searching" | "denied" | "unregistered" | "unknown";
  iccid?: Iccid | null;
  signal_dbm?: number | null;
  rsrp?: number | null;
  rsrq?: number | null;
  sinr?: number | null;
  discovery?: "qmi" | "at";
  manageable?: boolean;
  family?: string | null;
  imsi?: Imsi | null;
  home_plmn?: Plmn | null;
  serving_plmn?: Plmn | null;
  capability: CapabilitySummary;
}

export interface CapabilitySummary {
  sms_mo: "supported" | "degraded" | "unsupported" | "unknown";
  sms_mt: "supported" | "degraded" | "unsupported" | "unknown";
  matrix_version: string;
  reason?: string | null;
}

export interface CommandResultPayload {
  cmd_id: Uuid;
  status: "succeeded" | "failed" | "unknown" | "expired" | "cancelled";
  completed_at: number;
  attempts: number;
  reason_code?: string | null;
  reason?: string | null;
  details?: ContextValue | null;
}

export interface EsimInventoryPayload {
  modem_imei: Imei;
  eid: string;
  collected_at: number;
  profiles: Array<EsimProfile>;
}

export interface EsimProfile {
  iccid: Iccid;
  state: "enabled" | "disabled" | "deleted" | "unknown";
  nickname?: string | null;
}

export interface AlertPayload {
  level: "info" | "warning" | "error" | "critical";
  code: string;
  message: string;
  occurred_at: number;
  context: ContextValue;
}

export interface SendSmsCommand {
  kind: "SendSms";
  to: string;
  body: string;
  modem_imei?: Imei;
  iccid?: Iccid;
}

export interface RestartModemCommand {
  kind: "RestartModem";
  modem_imei: Imei;
}

export interface RunAtCommandCommand {
  kind: "RunAtCommand";
  modem_imei: Imei;
  command: string;
  timeout_ms?: number;
}

export interface SendUssdCommand {
  kind: "SendUssd";
  modem_imei: Imei;
  code: string;
  stage?: "start" | "continue" | "cancel";
}

export interface SetRadioCommand {
  kind: "SetRadio";
  modem_imei: Imei;
  enabled: boolean;
}

export interface ScanOperatorsCommand {
  kind: "ScanOperators";
  modem_imei: Imei;
}

export interface SelectOperatorCommand {
  kind: "SelectOperator";
  modem_imei: Imei;
  mode: "automatic" | "manual";
  plmn?: Plmn;
}

export interface ModemReportCommand {
  kind: "ModemReport";
  modem_imei: Imei;
}

export interface ResetModemUsbCommand {
  kind: "ResetModemUsb";
  modem_imei: Imei;
}

export interface SetDataNetworkCommand {
  kind: "SetDataNetwork";
  modem_imei: Imei;
  enabled: boolean;
}

export interface SetUsbnetModeCommand {
  kind: "SetUsbnetMode";
  modem_imei: Imei;
  mode: "rmnet" | "ecm" | "mbim" | "rndis";
}

export interface ReregisterNetworkCommand {
  kind: "ReregisterNetwork";
  modem_imei: Imei;
}

export interface RefreshModemsCommand {
  kind: "RefreshModems";
}

export interface ListEsimProfilesCommand {
  kind: "ListEsimProfiles";
  modem_imei: Imei;
}

export interface ConfigureProxyCommand {
  kind: "ConfigureProxy";
  instances: Array<ProxyInstanceSpec>;
  upstreams: Array<ProxyUpstreamSpec>;
}

export interface ProxyInstanceSpec {
  id: Uuid;
  name?: string;
  modem_imei: Imei;
  protocol: "socks5" | "http";
  listen_addr: string;
  listen_port: number;
  auth_enabled?: boolean;
  username?: string;
  password?: string;
  upstream_id?: string;
  enabled: boolean;
}

export interface ProxyUpstreamSpec {
  id: Uuid;
  name?: string;
  address: string;
  protocol: "socks5" | "http";
  username?: string;
  password?: string;
  enabled?: boolean;
}

export interface ProxyLifecycleCommand {
  kind: "ProxyLifecycle";
  instance_id: Uuid;
  action: "start" | "stop" | "restart";
}

export interface ProbeUpstreamProxyCommand {
  kind: "ProbeUpstreamProxy";
  upstream_id: Uuid;
}

export interface RotateIpCommand {
  kind: "RotateIp";
  modem_imei: Imei;
}

export interface SwitchEsimProfileCommand {
  kind: "SwitchEsimProfile";
  modem_imei: Imei;
  target_iccid: Iccid;
}

export interface UpdateCardPolicyCommand {
  kind: "UpdateCardPolicy";
  policy_version: string;
  policies: Array<CardPolicy>;
}

export interface CardPolicy {
  iccid: Iccid;
  cellular_enabled: boolean;
  vertical: "cn" | "intl";
  apn?: string | null;
}

export interface UpdateCapabilityMatrixCommand {
  kind: "UpdateCapabilityMatrix";
  matrix_version: string;
  matrix_sha256: Sha256;
  matrix: ContextValue;
}

export interface SelfUpdateCommand {
  kind: "SelfUpdate";
  version: string;
  url: HttpsUrl;
  sha256: Sha256;
  signature: string;
}

export interface ProtocolErrorPayload {
  code: "invalid_envelope" | "frame_too_large" | "unsupported_version" | "wrong_direction" | "device_id_mismatch" | "sequence_conflict" | "sequence_state_invalid" | "connection_superseded" | "rate_limited";
  message: string;
  related_message_id: Uuid | null;
  retryable: boolean;
  retry_after_ms?: number;
}

export type Command =
  | SendSmsCommand |
  | RestartModemCommand |
  | SwitchEsimProfileCommand |
  | ListEsimProfilesCommand |
  | RunAtCommandCommand |
  | SendUssdCommand |
  | SetRadioCommand |
  | ScanOperatorsCommand |
  | SelectOperatorCommand |
  | ModemReportCommand |
  | ResetModemUsbCommand |
  | SetDataNetworkCommand |
  | SetUsbnetModeCommand |
  | ReregisterNetworkCommand |
  | RefreshModemsCommand |
  | ConfigureProxyCommand |
  | ProxyLifecycleCommand |
  | ProbeUpstreamProxyCommand |
  | RotateIpCommand |
  | UpdateCardPolicyCommand |
  | UpdateCapabilityMatrixCommand |
  | SelfUpdateCommand;
