// Code generated by packages/contract/codegen/generate.py. DO NOT EDIT.

package contract

import "encoding/json"

const ProtocolVersion = 1
const SchemaID = "https://schemas.vodoge.cloud/edge-cloud/v1/edge-cloud.schema.json"
const WebSocketSubprotocol = "vodoge.edge.v1"

type MessageKind string

const (
	MessageKindResume          MessageKind = "Resume"
	MessageKindResumeAck       MessageKind = "ResumeAck"
	MessageKindUplinkAck       MessageKind = "UplinkAck"
	MessageKindUplinkGap       MessageKind = "UplinkGap"
	MessageKindUplinkGapAck    MessageKind = "UplinkGapAck"
	MessageKindPing            MessageKind = "Ping"
	MessageKindPong            MessageKind = "Pong"
	MessageKindCommandDeliver  MessageKind = "CommandDeliver"
	MessageKindCommandReceipt  MessageKind = "CommandReceipt"
	MessageKindSmsReceived     MessageKind = "SmsReceived"
	MessageKindSmsStatusReport MessageKind = "SmsStatusReport"
	MessageKindDeviceState     MessageKind = "DeviceState"
	MessageKindCommandResult   MessageKind = "CommandResult"
	MessageKindEsimInventory   MessageKind = "EsimInventory"
	MessageKindAlert           MessageKind = "Alert"
	MessageKindProxyTraffic    MessageKind = "ProxyTraffic"
	MessageKindProtocolError   MessageKind = "ProtocolError"
)

func (kind MessageKind) Sequenced() bool {
	switch kind {
	case MessageKindSmsReceived, MessageKindSmsStatusReport, MessageKindDeviceState, MessageKindCommandResult, MessageKindEsimInventory, MessageKindAlert, MessageKindProxyTraffic:
		return true
	default:
		return false
	}
}

type Envelope struct {
	V        int             `json:"v"`
	Kind     MessageKind     `json:"kind"`
	ID       string          `json:"id"`
	Ts       int64           `json:"ts"`
	DeviceID string          `json:"device_id"`
	Seq      *string         `json:"seq,omitempty"`
	TraceID  *string         `json:"trace_id,omitempty"`
	Payload  json.RawMessage `json:"payload"`
}

type SequenceRange struct {
	From    string `json:"from"`
	Through string `json:"through"`
}

type ResumePayload struct {
	ConnectionID            string   `json:"connection_id"`
	LastAssignedSeq         string   `json:"last_assigned_seq"`
	LowestRetainedSeq       *string  `json:"lowest_retained_seq"`
	LastAckedSeq            string   `json:"last_acked_seq"`
	PendingGapIds           []string `json:"pending_gap_ids"`
	CapabilityMatrixVersion string   `json:"capability_matrix_version"`
	EdgeVersion             *string  `json:"edge_version,omitempty"`
	QueueRecords            *int64   `json:"queue_records,omitempty"`
	QueueBytes              *int64   `json:"queue_bytes,omitempty"`
}

type ResumeAckPayload struct {
	ConnectionID     string          `json:"connection_id"`
	CommittedThrough string          `json:"committed_through"`
	MissingRanges    []SequenceRange `json:"missing_ranges"`
	MoreMissing      bool            `json:"more_missing"`
	MaxInFlight      int64           `json:"max_in_flight"`
	ServerTime       int64           `json:"server_time"`
}

type UplinkAckPayload struct {
	ConnectionID     string          `json:"connection_id"`
	CommittedThrough string          `json:"committed_through"`
	MissingRanges    []SequenceRange `json:"missing_ranges"`
	MoreMissing      bool            `json:"more_missing"`
	MaxInFlight      int64           `json:"max_in_flight"`
}

type UplinkGapPayload struct {
	GapID          string          `json:"gap_id"`
	Ranges         []SequenceRange `json:"ranges"`
	Reason         string          `json:"reason"`
	DroppedRecords int64           `json:"dropped_records"`
	OccurredAt     int64           `json:"occurred_at"`
	DropPolicy     string          `json:"drop_policy"`
	Detail         *string         `json:"detail,omitempty"`
}

type UplinkGapAckPayload struct {
	GapID            string  `json:"gap_id"`
	Accepted         bool    `json:"accepted"`
	CommittedThrough string  `json:"committed_through"`
	ReasonCode       *string `json:"reason_code,omitempty"`
}

type PingPayload struct {
	ConnectionID string `json:"connection_id"`
	SentAt       int64  `json:"sent_at"`
}

type PongPayload struct {
	ConnectionID string `json:"connection_id"`
	PingID       string `json:"ping_id"`
	ServerTime   int64  `json:"server_time"`
}

type CommandDeliverPayload struct {
	CmdID     string  `json:"cmd_id"`
	IssuedAt  int64   `json:"issued_at"`
	ExpiresAt int64   `json:"expires_at"`
	Attempt   *int64  `json:"attempt,omitempty"`
	Command   Command `json:"command"`
}

type CommandReceiptPayload struct {
	CmdID        string  `json:"cmd_id"`
	DeliveryID   string  `json:"delivery_id"`
	Status       string  `json:"status"`
	ReceivedAt   int64   `json:"received_at"`
	RetryAfterMs *int64  `json:"retry_after_ms,omitempty"`
	ReasonCode   *string `json:"reason_code,omitempty"`
}

type SmsReceivedPayload struct {
	ModemImei         string `json:"modem_imei"`
	Peer              string `json:"peer"`
	Body              string `json:"body"`
	ReceivedAt        int64  `json:"received_at"`
	Iccid             string `json:"iccid"`
	Bearer            string `json:"bearer"`
	Encoding          string `json:"encoding"`
	ModemStorageIndex *int64 `json:"modem_storage_index,omitempty"`
}

type SmsStatusReportPayload struct {
	ModemImei   string `json:"modem_imei"`
	Peer        string `json:"peer"`
	Reference   int64  `json:"reference"`
	Status      string `json:"status"`
	StatusCode  *int64 `json:"status_code,omitempty"`
	ReportedAt  int64  `json:"reported_at"`
	SubmittedAt *int64 `json:"submitted_at,omitempty"`
	DeliveredAt *int64 `json:"delivered_at,omitempty"`
}

type ProxyTrafficPayload struct {
	ReportedAt int64               `json:"reported_at"`
	Instances  []ProxyTrafficEntry `json:"instances"`
}

type ProxyTrafficEntry struct {
	InstanceID  string `json:"instance_id"`
	BytesUp     int64  `json:"bytes_up"`
	BytesDown   int64  `json:"bytes_down"`
	Connections int64  `json:"connections"`
	Errors      *int64 `json:"errors,omitempty"`
}

type DeviceStatePayload struct {
	ObservedAt int64        `json:"observed_at"`
	Modems     []ModemState `json:"modems"`
	Host       *HostState   `json:"host,omitempty"`
}

type HostState struct {
	PublicIp         *string  `json:"public_ip,omitempty"`
	CpuPercent       *float64 `json:"cpu_percent,omitempty"`
	MemoryUsedBytes  *int64   `json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes *int64   `json:"memory_total_bytes,omitempty"`
}

type ModemState struct {
	ModemImei    string            `json:"modem_imei"`
	State        string            `json:"state"`
	Registration string            `json:"registration"`
	Iccid        *string           `json:"iccid,omitempty"`
	SignalDbm    *int64            `json:"signal_dbm,omitempty"`
	Rsrp         *int64            `json:"rsrp,omitempty"`
	Rsrq         *int64            `json:"rsrq,omitempty"`
	Sinr         *int64            `json:"sinr,omitempty"`
	Discovery    *string           `json:"discovery,omitempty"`
	Manageable   *bool             `json:"manageable,omitempty"`
	Family       *string           `json:"family,omitempty"`
	Imsi         *string           `json:"imsi,omitempty"`
	HomePlmn     *string           `json:"home_plmn,omitempty"`
	ServingPlmn  *string           `json:"serving_plmn,omitempty"`
	Capability   CapabilitySummary `json:"capability"`
}

type CapabilitySummary struct {
	SmsMo         string  `json:"sms_mo"`
	SmsMt         string  `json:"sms_mt"`
	MatrixVersion string  `json:"matrix_version"`
	Reason        *string `json:"reason,omitempty"`
}

type CommandResultPayload struct {
	CmdID       string  `json:"cmd_id"`
	Status      string  `json:"status"`
	CompletedAt int64   `json:"completed_at"`
	Attempts    int64   `json:"attempts"`
	ReasonCode  *string `json:"reason_code,omitempty"`
	Reason      *string `json:"reason,omitempty"`
	Details     *any    `json:"details,omitempty"`
}

type EsimInventoryPayload struct {
	ModemImei   string        `json:"modem_imei"`
	Eid         string        `json:"eid"`
	CollectedAt int64         `json:"collected_at"`
	Profiles    []EsimProfile `json:"profiles"`
}

type EsimProfile struct {
	Iccid    string  `json:"iccid"`
	State    string  `json:"state"`
	Nickname *string `json:"nickname,omitempty"`
}

type AlertPayload struct {
	Level      string `json:"level"`
	Code       string `json:"code"`
	Message    string `json:"message"`
	OccurredAt int64  `json:"occurred_at"`
	Context    any    `json:"context"`
}

type SendSmsCommand struct {
	Kind      string  `json:"kind"`
	To        string  `json:"to"`
	Body      string  `json:"body"`
	ModemImei *string `json:"modem_imei,omitempty"`
	Iccid     *string `json:"iccid,omitempty"`
}

type RestartModemCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
}

type RunAtCommandCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
	Command   string `json:"command"`
	TimeoutMs *int64 `json:"timeout_ms,omitempty"`
}

type SendUssdCommand struct {
	Kind      string  `json:"kind"`
	ModemImei string  `json:"modem_imei"`
	Code      string  `json:"code"`
	Stage     *string `json:"stage,omitempty"`
}

type SetRadioCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
	Enabled   bool   `json:"enabled"`
}

type ScanOperatorsCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
}

type SelectOperatorCommand struct {
	Kind      string  `json:"kind"`
	ModemImei string  `json:"modem_imei"`
	Mode      string  `json:"mode"`
	Plmn      *string `json:"plmn,omitempty"`
}

type ModemReportCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
}

type ResetModemUsbCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
}

type SetDataNetworkCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
	Enabled   bool   `json:"enabled"`
}

type SetUsbnetModeCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
	Mode      string `json:"mode"`
}

type ReregisterNetworkCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
}

type RefreshModemsCommand struct {
	Kind string `json:"kind"`
}

type ListEsimProfilesCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
}

type ReadEsimInfoCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
}

type RetrieveEsimNotificationCommand struct {
	Kind           string `json:"kind"`
	ModemImei      string `json:"modem_imei"`
	SequenceNumber int64  `json:"sequence_number"`
}

type ConfigureProxyCommand struct {
	Kind      string              `json:"kind"`
	Instances []ProxyInstanceSpec `json:"instances"`
	Upstreams []ProxyUpstreamSpec `json:"upstreams"`
}

type ProxyInstanceSpec struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	ModemImei   string  `json:"modem_imei"`
	Protocol    string  `json:"protocol"`
	ListenAddr  string  `json:"listen_addr"`
	ListenPort  int64   `json:"listen_port"`
	AuthEnabled *bool   `json:"auth_enabled,omitempty"`
	Username    *string `json:"username,omitempty"`
	Password    *string `json:"password,omitempty"`
	UpstreamID  *string `json:"upstream_id,omitempty"`
	Enabled     bool    `json:"enabled"`
}

type ProxyUpstreamSpec struct {
	ID       string  `json:"id"`
	Name     *string `json:"name,omitempty"`
	Address  string  `json:"address"`
	Protocol string  `json:"protocol"`
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
	Enabled  *bool   `json:"enabled,omitempty"`
}

type ProxyLifecycleCommand struct {
	Kind       string `json:"kind"`
	InstanceID string `json:"instance_id"`
	Action     string `json:"action"`
}

type ProbeUpstreamProxyCommand struct {
	Kind       string `json:"kind"`
	UpstreamID string `json:"upstream_id"`
}

type RotateIpCommand struct {
	Kind      string `json:"kind"`
	ModemImei string `json:"modem_imei"`
}

type SwitchEsimProfileCommand struct {
	Kind        string `json:"kind"`
	ModemImei   string `json:"modem_imei"`
	TargetIccid string `json:"target_iccid"`
}

type UpdateCardPolicyCommand struct {
	Kind          string       `json:"kind"`
	PolicyVersion string       `json:"policy_version"`
	Policies      []CardPolicy `json:"policies"`
}

type CardPolicy struct {
	Iccid           string  `json:"iccid"`
	CellularEnabled bool    `json:"cellular_enabled"`
	Vertical        string  `json:"vertical"`
	Apn             *string `json:"apn,omitempty"`
}

type UpdateCapabilityMatrixCommand struct {
	Kind          string `json:"kind"`
	MatrixVersion string `json:"matrix_version"`
	MatrixSha256  string `json:"matrix_sha256"`
	Matrix        any    `json:"matrix"`
}

type SelfUpdateCommand struct {
	Kind      string `json:"kind"`
	Version   string `json:"version"`
	Url       string `json:"url"`
	Sha256    string `json:"sha256"`
	Signature string `json:"signature"`
}

type ProtocolErrorPayload struct {
	Code             string  `json:"code"`
	Message          string  `json:"message"`
	RelatedMessageID *string `json:"related_message_id"`
	Retryable        bool    `json:"retryable"`
	RetryAfterMs     *int64  `json:"retry_after_ms,omitempty"`
}

// Command is the payload of a CommandDeliver, passed through untouched.
//
// An alias, not a defined type. `type Command json.RawMessage` does not
// inherit RawMessage's MarshalJSON, so encoding/json fell back to the
// []byte rule and emitted the command as a base64 string. Every device
// rejected every command it was ever sent with "expected internally
// tagged enum Command", and since nothing read that log the commands
// simply stayed queued.
type Command = json.RawMessage

// FieldConstraint is one enum-constrained field inside a payload.
//
// Path uses dots for objects and `[]` for arrays, e.g. `modems[].state`.
type FieldConstraint struct {
	Path string
	Enum []string
}

// PayloadConstraints lists, per message kind, every field the schema
// constrains to a fixed set of values.
//
// Generated rather than written by hand: the hand-written version of this
// check knew about three fields, and those three were only discovered after
// twenty thousand envelopes had been stored with values outside the enum.
// A field added to the schema is covered here without anyone remembering to
// extend it.
var PayloadConstraints = map[MessageKind][]FieldConstraint{
	MessageKindUplinkGap: {
		{Path: "reason", Enum: []string{"queue_capacity", "storage_corruption", "operator_purge"}},
	},
	MessageKindCommandReceipt: {
		{Path: "status", Enum: []string{"accepted", "duplicate", "retry_later"}},
	},
	MessageKindSmsReceived: {
		{Path: "bearer", Enum: []string{"cs", "ims", "nas", "unknown"}},
		{Path: "encoding", Enum: []string{"gsm7", "ucs2", "8bit", "unknown"}},
	},
	MessageKindSmsStatusReport: {
		{Path: "status", Enum: []string{"delivered", "pending", "failed", "unknown"}},
	},
	MessageKindDeviceState: {
		{Path: "modems[].state", Enum: []string{"online", "offline", "recovering", "unknown"}},
		{Path: "modems[].registration", Enum: []string{"registered", "searching", "denied", "unregistered", "unknown"}},
		{Path: "modems[].discovery", Enum: []string{"qmi", "at"}},
		{Path: "modems[].capability.sms_mo", Enum: []string{"supported", "degraded", "unsupported", "unknown"}},
		{Path: "modems[].capability.sms_mt", Enum: []string{"supported", "degraded", "unsupported", "unknown"}},
	},
	MessageKindCommandResult: {
		{Path: "status", Enum: []string{"succeeded", "failed", "unknown", "expired", "cancelled"}},
	},
	MessageKindEsimInventory: {
		{Path: "profiles[].state", Enum: []string{"enabled", "disabled", "deleted", "unknown"}},
	},
	MessageKindAlert: {
		{Path: "level", Enum: []string{"info", "warning", "error", "critical"}},
	},
	MessageKindProtocolError: {
		{Path: "code", Enum: []string{"invalid_envelope", "frame_too_large", "unsupported_version", "wrong_direction", "device_id_mismatch", "sequence_conflict", "sequence_state_invalid", "connection_superseded", "rate_limited"}},
	},
}
